version: "3.5"

services:

  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ansible-docker_ansible_homedir:/ansible

volumes:
  ansible-docker_ansible_homedir:
    external: true
