version: "3.5"

services:

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
    volumes:
      - .:/workspace
      - ansible_homedir:/ansible

  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    volumes:
      - ansible_homedir:/root
      - ./playbook.yml:/root/playbook.yml
      - ./output/:/root/output

volumes:
  ansible_homedir:
