version: "3.5"

services:

  terraform-ansible:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    volumes:
      - .:/workspace
      - homedir:/root

volumes:
  homedir:
